plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Imrry\\Desktop\\humanizer\\3d-scroll-experience\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Imrry\\Desktop\\humanizer\\3d-scroll-experience"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]